DROP TABLE IF EXISTS `#__trials`;

CREATE TABLE `#__trials` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `alias` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `catid` int NOT NULL DEFAULT '0',
  `owner_user_id` int NOT NULL DEFAULT '0',
  `long_title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `descriptor` text,
  `status` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `status_full` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `supported_trial` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `support_role` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `follow-up-only` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `multi-single` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `funder` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `obstetric-neonatal` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `any_start` year DEFAULT NULL,
  `rec_start` year DEFAULT NULL,
  `rec_start_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `rec_end` year DEFAULT NULL,
  `rec_end_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `rec_target` varchar(255) DEFAULT NULL,
  `rec_total` int DEFAULT NULL,
  `rec_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `grant_start` date DEFAULT NULL,
  `grant_start_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `grant_end` year DEFAULT NULL,
  `grant_end_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `any_end` year DEFAULT NULL,
  `protocol_year` year DEFAULT NULL,
  `protocol_year_note` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `summary` text,
  `publications` text,
  `published_protocol` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `initial_source` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `summary_of_results` text,
  `other_files` text,
  `web_include` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `web_landing_include` varchar(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `web_home` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `eudract` varchar(255) DEFAULT NULL,
  `rec_ref` varchar(255) DEFAULT NULL,
  `isrctn` varchar(255) DEFAULT NULL,
  `ctu` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `controller` varchar(255) DEFAULT NULL,
  `duration` varchar(255) DEFAULT NULL,
  `logo_alt` varchar(255) DEFAULT NULL,
  `brand_id` int NOT NULL DEFAULT '0',
  `params` varchar(1024) NOT NULL DEFAULT '',
  `state` tinyint NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int NOT NULL DEFAULT '0',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int NOT NULL DEFAULT '0',
  `checked_out` int unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `access` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
)
    ENGINE          = MyISAM
    AUTO_INCREMENT  = 0
    DEFAULT CHARSET = utf8;
